
// Generated by Cadence Genus(TM) Synthesis Solution 21.17-s066_1
// Generated on: Apr  1 2025 16:59:05 EDT (Apr  1 2025 20:59:05 UTC)

// Verification Directory fv/alu_1bit 

module full_adder(Ai, Bi, Cini, Di, Couti);
  input Ai, Bi, Cini;
  output Di, Couti;
  wire Ai, Bi, Cini;
  wire Di, Couti;
  wire n_23;
  CLKBUFX20 drc_bufs(.A (n_23), .Y (Couti));
  ADDFHXL g94(.A (Bi), .B (Ai), .CI (Cini), .CO (n_23), .S (Di));
endmodule

module mux4to1(a, b, c, d, sel, out);
  input a, b, c, d;
  input [1:0] sel;
  output out;
  wire a, b, c, d;
  wire [1:0] sel;
  wire out;
  MX2X1 g39__5526(.A (sel[1]), .B (sel[0]), .S0 (b), .Y (out));
endmodule

module arithmetic_unit(Ai, Bi, Cini, sel, Di, Couti);
  input Ai, Bi, Cini;
  input [1:0] sel;
  output Di, Couti;
  wire Ai, Bi, Cini;
  wire [1:0] sel;
  wire Di, Couti;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       mux_out;
  full_adder FA(.Ai (Ai), .Bi (mux_out), .Cini (Cini), .Di (Di), .Couti
       (Couti));
  mux4to1 MUX_B(.a (UNCONNECTED_HIER_Z), .b (Bi), .c
       (UNCONNECTED_HIER_Z0), .d (UNCONNECTED_HIER_Z1), .sel (sel),
       .out (mux_out));
endmodule

module mux4to1_2_1(a, b, c, d, sel, out);
  input a, b, c, d;
  input [1:0] sel;
  output out;
  wire a, b, c, d;
  wire [1:0] sel;
  wire out;
  MX4XL g101__6783(.A (a), .B (c), .C (b), .D (d), .S0 (sel[1]), .S1
       (sel[0]), .Y (out));
endmodule

module logic_unit(Ai, Bi, sel, Ei);
  input Ai, Bi;
  input [1:0] sel;
  output Ei;
  wire Ai, Bi;
  wire [1:0] sel;
  wire Ei;
  wire [3:0] mux_inputs;
  wire n_0;
  mux4to1_2_1 MUX_LOGIC(.a (mux_inputs[0]), .b (mux_inputs[1]), .c
       (mux_inputs[2]), .d (n_0), .sel (sel), .out (Ei));
  INVXL g12(.A (Ai), .Y (n_0));
  NOR2BX1 g26__3680(.AN (mux_inputs[1]), .B (mux_inputs[0]), .Y
       (mux_inputs[2]));
  OR2XL g27__1617(.A (Bi), .B (Ai), .Y (mux_inputs[1]));
  AND2XL g28__2802(.A (Bi), .B (Ai), .Y (mux_inputs[0]));
endmodule

module mux4to1_2(a, b, c, d, sel, out);
  input a, b, c, d;
  input [1:0] sel;
  output out;
  wire a, b, c, d;
  wire [1:0] sel;
  wire out;
  wire n_1, n_2, n_3;
  CLKMX2X12 g101__1705(.A (n_1), .B (n_2), .S0 (sel[0]), .Y (n_3));
  MX2XL g102__5122(.A (b), .B (d), .S0 (sel[1]), .Y (n_2));
  MX2XL g103__8246(.A (a), .B (c), .S0 (sel[1]), .Y (n_1));
  CLKBUFX20 drc_bufs(.A (n_3), .Y (out));
endmodule

module alu_1bit(Ai, Bi, A_prev, A_next, Cini, sel, Fi, Couti);
  input Ai, Bi, A_prev, A_next, Cini;
  input [3:0] sel;
  output Fi, Couti;
  wire Ai, Bi, A_prev, A_next, Cini;
  wire [3:0] sel;
  wire Fi, Couti;
  wire Di, Ei, n_0, shift_left, shift_right;
  arithmetic_unit U_ARITH(.Ai (Ai), .Bi (Bi), .Cini (Cini), .sel
       (sel[1:0]), .Di (Di), .Couti (Couti));
  logic_unit U_LOGIC(.Ai (Ai), .Bi (Bi), .sel (sel[1:0]), .Ei (Ei));
  mux4to1_2 U_MUX(.a (Di), .b (Ei), .c (shift_right), .d (shift_left),
       .sel (sel[3:2]), .out (Fi));
  NOR2X1 g52__7098(.A (sel[2]), .B (n_0), .Y (shift_right));
  AND3XL g53__6131(.A (A_next), .B (sel[2]), .C (sel[3]), .Y
       (shift_left));
  NAND2X1 g54__1881(.A (A_prev), .B (sel[3]), .Y (n_0));
endmodule

